LOGGING:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout

    info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: simple
      filename: lidtk.info.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

    error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: simple
      filename: lidtk.errors.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

  loggers:
    my_module:
      level: ERROR
      handlers: [console]
      propagate: no

  root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]

# app_details:
#     app_name: "settings_app"
#     difficulty_level: "easy"
#     using_intermediate_rewards: True
#     tokens: ["Starbucks"]

device_details:
  device_name: "android"

# app_details:
#   app_name: "split_app"
#   difficulty_level: "easy"
#   using_intermediate_rewards: True
#   tokens: ["AppBuddy","Samsung","RatTraining","100"]

app_details:
  app_name: "alarm_app"
  difficulty_level: "easy"
  using_intermediate_rewards: True
  tokens: ["7:58","9:49","6:15"]

# app_details:
#   app_name: "shopping_app"
#   difficulty_level: "easy"
#   using_intermediate_rewards: True
#   tokens: ["Brunch","Milk","Eggs"] 


